#ifndef GPS_PRINTER_EVENTS_H_
#define GPS_PRINTER_EVENTS_H_

#define GPS_PRINTER_RESERVED_INF_EID (0)
#define GPS_PRINTER_STARTUP_INF_EID  (1)

#define GPS_PRINTER_RESERVED_ERR_EID (10)
#define GPS_PRINTER_STARTUP_ERR_EID  (11)

#endif // GPS_PRINTER_EVENTS_H_
